In [ ]:
%pylab

In [10]:
A = array(
    [[1,0,1,0],
     [3,0,0,2],
     [0,2,1,1]])

In [13]:
print A
print A.shape
print A.ndim
print type(A)

[[1 0 1 0]
 [3 0 0 2]
 [0 2 1 1]]
(3, 4)
2
<type 'numpy.ndarray'>


In [14]:
v = array([-1, -5/4., 1, 3/2.])

In [15]:
dot(A,v)

array([ 0.,  0.,  0.])